spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: username
      password: password
  datasource:
    url: jdbc:h2:mem:testdb